modLoader="javafml"
loaderVersion="[0,)"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/ArcaneTools/issues"

[[mixins]]
config="arcanetools.neoforge.mixins.json"

[[mods]]
modId="arcanetools"
version="${modVersion}"
displayName="Arcane Tools"
#updateJSONURL="Modrinth PLEASE add this in the future."
displayURL="https://github.com/TonimatasDEV/ArcaneTools"
logoFile="logo.png"
credits="TonimatasDEV - Developer"
authors="TonimatasDEV"
description='''
Indestructible, upgradeable tools infused with arcane for Minecraft. Enhance speed, damage, reach, and other abilities using the durability.
'''

[[dependencies.arcanetools]]
modId="neoforge"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.arcanetools]]
modId="minecraft"
type="required"
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"
